### ISSUE TITLE
implies should override default

### ISSUE THREAD

**Issue by SineSwiper** [rjbs/Getopt-Long-Descriptive#12]
Consider this case:

```
[ 'a' => "Option A.  Off by default." => { default => 0 } ],
[ 'b' => "Option B.  Implies 'a'."    => { default => 0, implies => 'a' } ],
```

This option set ran as-is (using "cmd -b") would error with:

```
option specification for b implies that a should be set to '1', but it is '0' already
```

It's only zero because the default is zero.  However, with option B enabled, the 'implies' attr should override the default.

**Comment by rjbs** [comment]
I just pushed up 1edbd52, which was more complex than I'd hoped… I'll think about whether I want to ship that.  What do you think?

**Comment by SineSwiper** [comment]
Sorry for the late reply, but that looks good.  And I see it's hit master and CPAN.  I'll close.
