### ISSUE TITLE
:+ argument specification displays as [=STR] instead of [=INT]

### ISSUE THREAD

**Issue by gordon-fish** [rjbs/Getopt-Long-Descriptive#24]
I noticed that when using 'foo:+' for the format, the usage text shows --foo[=STR] when it should show --foo[=INT] based on the [documentation for Getopt::Long](https://metacpan.org/pod/Getopt::Long#:-+-[-desttype-])

'foo:i', however, generations --foo[=INT] as expected.

**Comment by gordon-fish** [comment]
This problem also applies to 'foo:5' [See this part of Getopt::Long](https://metacpan.org/pod/Getopt::Long#:-number-[-desttype-])

Here is a simple patch that fixes this in Descriptive/Usage.pm:
    @@ -208,6 +208,7 @@
             }
         }
         if (substr($assign_spec, 0, 1) eq ':') {
    +        $result = 'INT' if substr($assign_spec, 0, 2) =~ /^:(\+|\d+)/;
             return "[=$result]";
         }
         # with leading space so it can just blindly be appended.

**Comment by gordon-fish** [comment]
Here is a copy of the patch I made: https://gist.github.com/gordon-fish/1017db95e4bc159ffbde39dc439d087d

**Comment by rjbs** [comment]
Thanks, I've made `:+` and `:1` produce `[=INT]`.  This should ship soon.

**Comment by gordon-fish** [comment]
Thanks!
