### ISSUE TITLE
inconsistent perl version requirement

### ISSUE THREAD

**Issue by haarg** [rjbs/Getopt-Long-Descriptive#41]
The module includes a line `use v5.10.1;`, but actually requires perl 5.12. This was changed in the latest release, 0.110. The changes entry for this release only notes "just small packaging updates", not noting the perl requirement bump. The actual need for the new version is due to using `package NAMESPACE VERSION` syntax, which was added automatically by the Dist::Zilla setup.

It feels like the perl version bump wasn't entirely intentional, so perhaps the use of `package NAMESPACE VERSION` syntax should be removed. Alternatively, the `use v5.10.1;` line should be updated and Changes entry for 0.110 should be amended to note the perl prereq bump.

**Comment by rjbs** [comment]
Yeah, probably this has been happening to a number of my recently re-released libraries that were updated to get metadata corrected.  I'm okay with the bump happening, though, and I'll make a little update.
